// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID                 int32         `db:"id" json:"id"`
	UserID             int32         `db:"user_id" json:"userID"`
	Name               string        `db:"name" json:"name"`
	Type               string        `db:"type" json:"type"`
	Price              float32       `db:"price" json:"price"`
	TaxPercentage      float32       `db:"tax_percentage" json:"taxPercentage"`
	Installment        sql.NullInt32 `db:"installment" json:"installment"`
	InstallmentEndDate sql.NullTime  `db:"installment_end_date" json:"installmentEndDate"`
	CreatedAt          time.Time     `db:"created_at" json:"createdAt"`
}

type User struct {
	ID            int32          `db:"id" json:"id"`
	Email         string         `db:"email" json:"email"`
	ChatID        string         `db:"chat_id" json:"chatID"`
	SpreadsheetID sql.NullString `db:"spreadsheet_id" json:"spreadsheetID"`
	CreatedAt     time.Time      `db:"created_at" json:"createdAt"`
}
