// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package repository

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, email, chat_id, spreadsheet_id, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ChatID,
		&i.SpreadsheetID,
		&i.CreatedAt,
	)
	return &i, err
}
