// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id int32) (*User, error)
}

var _ Querier = (*Queries)(nil)
